name: Build Custom APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اسم التطبيق'
        required: true
      website_url:
        description: 'رابط الموقع'
        required: true

env:
  APP_NAME: ${{ github.event.inputs.app_name }}
  WEBSITE_URL: ${{ github.event.inputs.website_url }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Configure App
        run: |
          sed -i "s/__APP_NAME__/$APP_NAME/g" app/src/main/res/values/strings.xml
          sed -i "s|__WEBSITE_URL__|$WEBSITE_URL|g" app/src/main/res/values/strings.xml
          sed -i "s/__PRIMARY_COLOR__/#2196F3/g" app/src/main/res/values/colors.xml

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_NAME }}
          path: app/build/outputs/apk/debug/app-debug.apk