name: Build APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
      website_url:
        description: 'Website URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Replace Placeholders
        run: |
          sed -i "s/__APP_NAME__/${{ github.event.inputs.app_name }}/g" app/src/main/res/values/strings.xml
          sed -i "s|__WEBSITE_URL__|${{ github.event.inputs.website_url }}|g" app/src/main/res/values/strings.xml

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: GeneratedApp
          path: app/build/outputs/apk/debug/app-debug.apk
