name: Build APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اسم التطبيق'
        required: true
      website_url:
        description: 'رابط الموقع'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Check Files in Workspace
        run: ls -lah

      - name: Replace Placeholders
        run: |
          sed -i "s/__APP_NAME__/${{ github.event.inputs.app_name }}/g" App/src/main/res/values/strings.xml
          sed -i "s|__WEBSITE_URL__|${{ github.event.inputs.website_url }}|g" App/src/main/res/values/strings.xml

      - name: Set Execution Permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :App:assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GeneratedApp
          path: App/build/outputs/apk/debug/app-debug.apk
