name: Build APK

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'اسم التطبيق'
        required: true
      website_url:
        description: 'رابط الموقع'
        required: true
      email:
        description: 'البريد الإلكتروني'
        required: true
      phone:
        description: 'رقم الهاتف'
        required: true
      address:
        description: 'العنوان'
        required: false
      privacy_url:
        description: 'رابط سياسة الخصوصية'
        required: true
      app_version:
        description: 'إصدار التطبيق'
        required: true
      primary_color:
        description: 'اللون الرئيسي'
        required: true
      secondary_color:
        description: 'اللون الثانوي'
        required: true
      app_logo:
        description: 'شعار التطبيق (Base64)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Decode Logo
        run: |
          echo "${{ github.event.inputs.app_logo }}" | base64 -d > app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

      - name: Replace Placeholders
        run: |
          sed -i "s/__APP_NAME__/${{ github.event.inputs.app_name }}/g" app/src/main/res/values/strings.xml
          sed -i "s|__WEBSITE_URL__|${{ github.event.inputs.website_url }}|g" app/src/main/res/values/strings.xml
          sed -i "s/__EMAIL__/${{ github.event.inputs.email }}/g" app/src/main/res/values/strings.xml
          sed -i "s/__PHONE__/${{ github.event.inputs.phone }}/g" app/src/main/res/values/strings.xml
          sed -i "s/__ADDRESS__/${{ github.event.inputs.address }}/g" app/src/main/res/values/strings.xml
          sed -i "s|__PRIVACY_URL__|${{ github.event.inputs.privacy_url }}|g" app/src/main/res/values/strings.xml
          sed -i "s/__PRIMARY_COLOR__/${{ github.event.inputs.primary_color }}/g" app/src/main/res/values/colors.xml
          sed -i "s/__SECONDARY_COLOR__/${{ github.event.inputs.secondary_color }}/g" app/src/main/res/values/colors.xml

      - name: Set Execution Permission
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GeneratedApp
          path: app/build/outputs/apk/debug/app-debug.apk
